# Generated by Django 6.0.2 on 2026-02-08 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dados_produtividade", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        help_text="Keyword to match in activity description (case-insensitive)",
                        max_length=100,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority rules run first"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dados_produtividade.category",
                    ),
                ),
            ],
        ),
    ]
